[package]
name = "vodozemac-ios"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
vodozemac = { git = "https://github.com/matrix-org/vodozemac" }
serde_json = "1.0.128"

[lib]
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.24.0"